name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get the latest gitolite release tag
      run: echo "GITOLITE_VERSION=$(curl -s 'https://api.github.com/repos/sitaramc/gitolite/tags' | jq -r .[0].name)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build --build-arg GITOLITE_VERSION="${{ GITOLITE_VERSION }}" --tag gitolite:"${{ GITOLITE_VERSION }}" --tag gitolite:latest --file Dockerfile .
